force-app/packaged/main/default/objects/Manifest__c/Manifest__c.object-meta.xml
<CustomObject>
    <label>Manifest</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Manifest__c/fields/Trialforce_Template__c.field-meta.xml
<CustomField>
    <fullName>Trialforce_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trialforce Template</label>
    <referenceTo>Trialforce_Template__c</referenceTo>
    <relationshipLabel>Manifests</relationshipLabel>
    <relationshipName>Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/packaged/main/default/objects/Manifest_Package__c/Manifest_Package__c.object-meta.xml
<CustomObject>
    <label>Manifest Package</label>
    <nameField>
        <displayFormat>MP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manifest Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Manifest_Package__c/fields/Manifest__c.field-meta.xml
<CustomField>
    <fullName>Manifest__c</fullName>
    <label>Manifest</label>
    <referenceTo>Manifest__c</referenceTo>
    <relationshipLabel>Manifest Packages</relationshipLabel>
    <relationshipName>Manifest_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/packaged/main/default/objects/Manifest_Package__c/fields/Package_Version__c.field-meta.xml
<CustomField>
    <fullName>Package_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sfLma__Package_Version__c.sfLma__Package__c</field>
            <operation>equals</operation>
            <valueField>$Source.Package__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sfLma__Package_Version__c</referenceTo>
    <relationshipLabel>Provisioning Manifest Packages</relationshipLabel>
    <relationshipName>Manifest_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/Provisioning_Request__c.object-meta.xml
<CustomObject>
    <label>Provisioning Request</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisioning Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/PreferredEdition__c.field-meta.xml
<CustomField>
    <fullName>PreferredEdition__c</fullName>
    <label>Preferred Edition</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/PreferredLanguage__c.field-meta.xml
<CustomField>
    <fullName>PreferredLanguage__c</fullName>
    <label>Preferred Language</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/SignupEmail__c.field-meta.xml
<CustomField>
    <fullName>SignupEmail__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provisioning_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Subdomain__c.field-meta.xml
<CustomField>
    <fullName>Subdomain__c</fullName>
    <label>Subdomain</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/TrialDays__c.field-meta.xml
<CustomField>
    <fullName>TrialDays__c</fullName>
    <defaultValue>365</defaultValue>
    <label>Trial Days</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Trialforce_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Trialforce_Template_Id__c</fullName>
    <label>Trialforce Template Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request_Package__c/Provisioning_Request_Package__c.object-meta.xml
<CustomObject>
    <label>Provisioning Request Package</label>
    <nameField>
        <displayFormat>PRP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisioning Request Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Provisioning_Request_Package__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <label>Package Install Job Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request_Package__c/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request_Package__c/fields/Ordinal__c.field-meta.xml
<CustomField>
    <fullName>Ordinal__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Ordinal</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request_Package__c/fields/Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Package_Version_Id__c</fullName>
    <label>Package Version Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request_Package__c/fields/Provisioning_Request__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Request__c</fullName>
    <label>Provisioning Request</label>
    <referenceTo>Provisioning_Request__c</referenceTo>
    <relationshipLabel>Provisioning Request Packages</relationshipLabel>
    <relationshipName>Provisioning_Request_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/packaged/main/default/objects/sfLma__Package_Version__c/fields/Package_Version_Password__c.field-meta.xml
<CustomField>
    <fullName>Package_Version_Password__c</fullName>
    <label>Package Version Password</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/Subscriber_Authentication__c.object-meta.xml
<CustomObject>
    <label>Subscriber Authentication</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers Authentication</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <label>Instance</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <label>Org Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/Refresh__c.field-meta.xml
<CustomField>
    <fullName>Refresh__c</fullName>
    <label>Refresh</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/packaged/main/default/objects/Trialforce_Template__c/Trialforce_Template__c.object-meta.xml
<CustomObject>
    <label>Trialforce Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trialforce Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Trialforce_Template__c/fields/Trialforce_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Trialforce_Template_Id__c</fullName>
    <label>Trialforce Template Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/globalValueSets/Provisioning_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Succeeded</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <masterLabel>Provisioning Status</masterLabel>
</GlobalValueSet>

force-app/packaged/main/default/classes/ProvisioningRequestHandler.cls
public with sharing class ProvisioningRequestHandler
{
    public class ComponentResponse
    {
        @AuraEnabled
        public string Message { get; set; }
        @AuraEnabled
        public string MessageType { get; set; }
        @AuraEnabled
        public boolean ForceRefresh { get; set; }
    }

    @InvocableMethod(label='Create Provisioning Request')
    public static void CreateProvisioningRequest(List<ProvisioningRequest> requests)
    {
        ProvisioningRequest request = requests[0];
        // need to bulkify

        CreateProvisioningRequest(request.manifestId, request.company, request.country, request.firstname, request.lastname, request.notes, request.edition, request.language, request.email, request.subdomain, request.trialdays, request.username);
    }

    public static void CreateProvisioningRequest(string manifestId, string company, string country, string firstname, string lastname, string notes, string edition, string language, string email, string subdomain, integer trialdays, string username)
    {
        Provisioning_Request__c provisioningRequest = new Provisioning_Request__c
        (
            Company__c = company,
            Country__c = country,
            FirstName__c = firstname,
            LastName__c = lastname,
            Notes__c = notes,
            PreferredEdition__c = edition,
            PreferredLanguage__c = language,
            SignupEmail__c = email,
            Subdomain__c = subdomain,
            TrialDays__c = trialdays,
            Username__c = username
        );

        if(string.isNotEmpty(manifestId))
        {
            List<Manifest__c> manifests = [SELECT Id, Name, Trialforce_Template__r.Trialforce_Template_Id__c, (SELECT Ordinal__c, Package_Version__r.sfLma__Version_ID__c, Package_Version__r.Package_Version_Password__c, Package_Version__r.sfLma__Package__r.Namespace__c FROM Manifest_Packages__r) FROM Manifest__c WHERE Id =: manifestId];

            if(!manifests.isEmpty())
            {
                Manifest__c manifest = manifests.get(0);

                if(manifest.Trialforce_Template__r != null)
                {
                    provisioningRequest.Trialforce_Template_Id__c = manifest.Trialforce_Template__r.Trialforce_Template_Id__c;
                    provisioningRequest.PreferredEdition__c = null;
                }

                database.insert(provisioningRequest, true);

                List<Provisioning_Request_Package__c> provisioningRequestPackages = new List<Provisioning_Request_Package__c>();

                for(Manifest_Package__c manifestPackage : manifest.Manifest_Packages__r)
                {
                    Provisioning_Request_Package__c provisioningRequestPackage = new Provisioning_Request_Package__c
                    (
                        Namespace__c = manifestPackage.Package_Version__r.sfLma__Package__r.Namespace__c,
                        Ordinal__c = manifestPackage.Ordinal__c,
                        Package_Version_Id__c = manifestPackage.Package_Version__r.sfLma__Version_ID__c,
                        Package_Version_Password__c = manifestPackage.Package_Version__r.Package_Version_Password__c,
                        Provisioning_Request__c = provisioningRequest.Id
                    );

                    provisioningRequestPackages.add(provisioningRequestPackage);
                }

                
                database.insert(provisioningRequestPackages, true);
            }
        }
    }

    public static void CreateOrgSignupRequest(Provisioning_Request__c provisioningRequest)
    {
        string client_id = AuthHelper.CLIENTID;
        string client_secret = AuthHelper.CLIENTSECRET;
        string callback_url = AuthHelper.REDIRECTURL;


        Map<string, object> dataMap = new Map<string, object>();
        dataMap.put('Company', provisioningRequest.Company__c);
        dataMap.put('ShouldConnectToEnvHub', true);
        dataMap.put('Country', provisioningRequest.Country__c);
        dataMap.put('SignupEmail', provisioningRequest.SignupEmail__c);
        dataMap.put('FirstName', provisioningRequest.FirstName__c);
        dataMap.put('LastName', provisioningRequest.LastName__c);
        dataMap.put('Subdomain', provisioningRequest.Subdomain__c);
        dataMap.put('IsSignupEmailSuppressed', true);
        dataMap.put('TrialDays', provisioningRequest.TrialDays__c);
        dataMap.put('Username', provisioningRequest.Username__c);
        dataMap.put('PreferredLanguage', provisioningRequest.PreferredLanguage__c);

        if(provisioningRequest.Trialforce_Template_Id__c != null)
        {
            dataMap.put('TemplateId', provisioningRequest.Trialforce_Template_Id__c);
        }
        else 
        {
            dataMap.put('Edition', provisioningRequest.PreferredEdition__c);
        }

        dataMap.put('ConnectedAppCallbackUrl', callback_url);
        dataMap.put('ConnectedAppConsumerKey', client_id);


        try 
        {
            Type objType = Type.forName('SignupRequest');

            sObject signupRequest = (sObject)JSON.deserialize(JSON.serialize(dataMap), objType);

            if(!Test.isRunningTest())
            {
                insert signupRequest;

                provisioningRequest.Status__c = 'In Progress';
            }
        } 
        catch (Exception ex) 
        {
            // this is an org where SignupRequest does not exist
            provisioningRequest.Notes__c = ex.getMessage();
            provisioningRequest.Status__c = 'Failed';
        }
        finally
        {
            update provisioningRequest;
        }
    }

    public static List<CustomPicklist> getPickListValues(string objName, string fieldName)
    {
        List<CustomPicklist> picklistSet = new List<CustomPicklist>();
        CustomPicklist defaultOption = new CustomPicklist('Please select', '');

        Type objType = Type.forName(objName);

        if(objType != null)
        {
            sObject objInstance = (sObject)objType.newInstance();
            
            if(objInstance != null)
            {
                Schema.DescribeFieldResult fieldResult = objInstance.getsObjectType().getDescribe().fields.getMap().get(fieldName).getDescribe();
                
                for(Schema.PicklistEntry pickListValue: fieldResult.getPicklistValues())
                {
                    picklistSet.add(new CustomPicklist(pickListValue.value, pickListValue.label));
                }
            }
        }
    
        return picklistSet;
    }

    @AuraEnabled
    public static ComponentResponse checkPackageInstall(string record_id)
    {
        ComponentResponse response = new ComponentResponse();
        Provisioning_Request_Package__c provisioningRequestPackage;
        Subscriber_Authentication__c authRecord;

        boolean refreshedTokens;

        List<Provisioning_Request_Package__c> provisioningRequestPackages = [SELECT Package_Version_Id__c, Package_Version_Password__c, Provisioning_Request__r.Org_Id__c, Job_Id__c FROM Provisioning_Request_Package__c WHERE Id =: record_id];

        if(!provisioningRequestPackages.isEmpty())
        {
            provisioningRequestPackage = provisioningRequestPackages[0];

            List<Subscriber_Authentication__c> authRecords = [SELECT Access__c, Instance__c, Refresh__c, Org_Id__c, User__c FROM Subscriber_Authentication__c WHERE Org_Id__c =: provisioningRequestPackage.Provisioning_Request__r.Org_Id__c];

            if(!authRecords.isEmpty())
            {
                authRecord = authRecords[0];

                try 
                {
                    Map<string, object> responseMap;

                    responseMap = convertToMap(ToolingApiHelper.createPackageInstallStatusRequest(authRecord, provisioningRequestPackage));

                    if(responseMap.containsKey('errorCode') && responseMap.get('errorCode') == 'INVALID_SESSION_ID')
                    {
                        authRecord = AuthHelper.refreshAccessToken(authRecord, true);
                        refreshedTokens = true;

                        responseMap = convertToMap(ToolingApiHelper.createPackageInstallStatusRequest(authRecord, provisioningRequestPackage));
                    }
                    
                    if(responseMap.containsKey('Status'))
                    {
                        string status = responseMap.get('Status').toString();

                        if(status == 'InProgress')
                        {
                            response.Message = 'The package install is in progress';
                            response.MessageType = 'info';
                        }
                        else if(status == 'Error')
                        {
                            response.Message = 'The package install has failed';
                            response.MessageType = 'error';
                            response.ForceRefresh = true;
                        }
                        else if(status == 'Success')
                        {
                            response.Message = 'The package install has succeeded';
                            response.MessageType = 'success';
                            response.ForceRefresh = true;
                        }
                        else 
                        {
                            response.Message = 'The package install status is unknown';
                            response.MessageType = 'warning';
                        }
                    }
                }
                catch (Exception ex)
                {
                    response.Message = ex.getStackTraceString();
                    response.Message += '\r\n' + ex.getMessage();
                    response.MessageType = 'error';
                }
            }
        }

        if(refreshedTokens == true)
        {
            AuthHelper.refreshAccessToken(authRecord, false);
        }

        if(response.MessageType == 'error')
        {
            provisioningRequestPackage.Status__c = 'Failed';
            
        }
        else if(response.MessageType == 'success')
        {
            provisioningRequestPackage.Status__c = 'Succeeded';
        }

        provisioningRequestPackage.Notes__c = response.Message;
        upsert provisioningRequestPackage;

        return response;
    }

    @AuraEnabled
    public static ComponentResponse InstallPackage(string record_id)
    {
        ComponentResponse response = new ComponentResponse();
        Provisioning_Request_Package__c provisioningRequestPackage;
        Subscriber_Authentication__c authRecord;

        boolean refreshedTokens;
        
        List<Provisioning_Request_Package__c> provisioningRequestPackages = [SELECT Package_Version_Id__c, Package_Version_Password__c, Provisioning_Request__r.Org_Id__c FROM Provisioning_Request_Package__c WHERE Id =: record_id];

        if(!provisioningRequestPackages.isEmpty())
        {
            provisioningRequestPackage = provisioningRequestPackages[0];

            List<Subscriber_Authentication__c> authRecords = [SELECT Access__c, Instance__c, Refresh__c, Org_Id__c, User__c FROM Subscriber_Authentication__c WHERE Org_Id__c =: provisioningRequestPackage.Provisioning_Request__r.Org_Id__c];

            if(!authRecords.isEmpty())
            {
                authRecord = authRecords[0];

                try 
                {
                    Map<string, object> responseMap;

                    responseMap = convertToMap(ToolingApiHelper.createPackageInstallRequest(authRecord, provisioningRequestPackage));

                    if(responseMap.containsKey('errorCode') && responseMap.get('errorCode') == 'INVALID_SESSION_ID')
                    {
                        authRecord = AuthHelper.refreshAccessToken(authRecord, true);
                        refreshedTokens = true;

                        responseMap = convertToMap(ToolingApiHelper.createPackageInstallRequest(authRecord, provisioningRequestPackage));
                    }

                    if(responseMap.containsKey('success') && responseMap.get('success') == true &&
                        responseMap.containsKey('id'))
                    {
                        provisioningRequestPackage.Job_Id__c = responseMap.get('id').toString();

                        response.Message = 'Successful request!';
                        response.MessageType = 'success';
                        response.ForceRefresh = true;
                    }

                }
                catch (Exception ex)
                {
                    response.Message = ex.getStackTraceString();
                    response.MessageType = 'error';
                }
            }
            else 
            {
                response.Message = 'There are no authentication credentials available for this org';
                response.MessageType = 'error';
            }
        }
        else 
        {
            response.Message = 'There are no provisioning packages found';
            response.MessageType = 'error';
        }

        // needs to be done here so there are no uncommitted changes before a callout.
        if(refreshedTokens == true)
        {
            AuthHelper.refreshAccessToken(authRecord, false);
        }

        if(response.MessageType == 'error')
        {
            provisioningRequestPackage.Status__c = 'Failed';
            
        }
        else if(response.MessageType == 'success')
        {
            provisioningRequestPackage.Status__c = 'In Progress';
        }

        provisioningRequestPackage.Notes__c = response.Message;
        upsert provisioningRequestPackage;

        return response;
        
    }

    static Map<string, object> convertToMap(string response)
    {
        system.debug(response);

        if(response.startsWith('['))
        {
            List<object> responseListMap = convertToListMap(response);
            return convertToMap(responseListMap[0]);
        }

        return (Map<string, object>)JSON.deserializeUntyped(response);
    }

    static Map<string, object> convertToMap(object response)
    {
        return (Map<string, object>)JSON.deserializeUntyped(JSON.serialize(response));
    }

    static List<object> convertToListMap(string response)
    {
        return (List<object>)JSON.deserializeUntyped(response);
    }

    @AuraEnabled(cacheable=true)
    public static ComponentResponse fetchUserInfo(string access_token)
    {
        ComponentResponse response = new ComponentResponse();

        string userInfoUrl = 'https://login.salesforce.com/services/oauth2/userinfo';
        
        HttpRequest request = new HttpRequest();
        request.setEndpoint(userInfoUrl);
        request.setMethod('GET');
        request.setHeader('Authorization', 'Bearer ' + access_token);

        Http http = new Http();
        HttpResponse httpresponse = http.send(request);
        
        Map<string, object> responseMap = convertToMap(httpresponse.getBody());

        if(responseMap.containsKey('user_id'))
        {
            response.Message = 'Authentication Details are currently valid';
            response.MessageType = 'success';
        }
        else
        {
            response.Message = 'Authentication Details are currently invalid';
            response.MessageType = 'error';
        }
        
        return response;
    }
}