force-app/packaged/main/default/objects/Manifest__c/Manifest__c.object-meta.xml
<CustomObject>
    <label>Manifest</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Manifest__c/fields/Trialforce_Template__c.field-meta.xml
<CustomField>
    <fullName>Trialforce_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trialforce Template</label>
    <referenceTo>Trialforce_Template__c</referenceTo>
    <relationshipLabel>Manifests</relationshipLabel>
    <relationshipName>Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/packaged/main/default/objects/Manifest_Package__c/Manifest_Package__c.object-meta.xml
<CustomObject>
    <label>Manifest Package</label>
    <nameField>
        <displayFormat>MP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manifest Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Manifest_Package__c/fields/Manifest__c.field-meta.xml
<CustomField>
    <fullName>Manifest__c</fullName>
    <label>Manifest</label>
    <referenceTo>Manifest__c</referenceTo>
    <relationshipLabel>Manifest Packages</relationshipLabel>
    <relationshipName>Manifest_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/packaged/main/default/objects/Manifest_Package__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>sfLma__Package__c</referenceTo>
    <relationshipLabel>Manifest Packages</relationshipLabel>
    <relationshipName>Manifest_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/packaged/main/default/objects/Manifest_Package__c/fields/Package_Version__c.field-meta.xml
<CustomField>
    <fullName>Package_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sfLma__Package_Version__c.sfLma__Package__c</field>
            <operation>equals</operation>
            <valueField>$Source.Package__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sfLma__Package_Version__c</referenceTo>
    <relationshipLabel>Provisioning Manifest Packages</relationshipLabel>
    <relationshipName>Manifest_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/Provisioning_Request__c.object-meta.xml
<CustomObject>
    <label>Provisioning Request</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisioning Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/PreferredEdition__c.field-meta.xml
<CustomField>
    <fullName>PreferredEdition__c</fullName>
    <label>Preferred Edition</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/PreferredLanguage__c.field-meta.xml
<CustomField>
    <fullName>PreferredLanguage__c</fullName>
    <label>Preferred Language</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/SignupEmail__c.field-meta.xml
<CustomField>
    <fullName>SignupEmail__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provisioning_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Subdomain__c.field-meta.xml
<CustomField>
    <fullName>Subdomain__c</fullName>
    <label>Subdomain</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/TrialDays__c.field-meta.xml
<CustomField>
    <fullName>TrialDays__c</fullName>
    <defaultValue>365</defaultValue>
    <label>Trial Days</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Trialforce_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Trialforce_Template_Id__c</fullName>
    <label>Trialforce Template Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Request__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/sfLma__Package__c/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/sfLma__Package_Version__c/fields/Package_Version_Password__c.field-meta.xml
<CustomField>
    <fullName>Package_Version_Password__c</fullName>
    <label>Package Version Password</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/packaged/main/default/objects/Trialforce_Template__c/Trialforce_Template__c.object-meta.xml
<CustomObject>
    <label>Trialforce Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trialforce Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Trialforce_Template__c/fields/Trialforce_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Trialforce_Template_Id__c</fullName>
    <label>Trialforce Template Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/globalValueSets/Provisioning_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Succeeded</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <masterLabel>Provisioning Status</masterLabel>
</GlobalValueSet>

force-app/packaged/main/default/classes/ProvisioningRequestHandlerTest.cls
@isTest
public with sharing class ProvisioningRequestHandlerTest
{
    @isTest
    static void createSignupRequestTest()
    {
        sfLma__Package__c packageObj = new sfLma__Package__c
        (
            Name = 'Test Package 1',
            Namespace__c = 'aprv'
        );
        insert packageObj;

        sfLma__Package_Version__c packageVersion = new sfLma__Package_Version__c
        (
            sfLma__Package__c = packageObj.Id,
            Name = 'Test Package 1 v1',
            sfLma__Release_Date__c = system.today(),
            sfLma__Sequence__c = 1,
            sfLma__Version__c = '04t4J000000FPjXQAW',
            sfLma__Version_ID__c = '04t4J000000FPjXQAW',
            Package_Version_Password__c = ''
        );
        insert packageVersion;

        sfLma__Package_Version__c packageVersion2 = new sfLma__Package_Version__c
        (
            sfLma__Package__c = packageObj.Id,
            Name = 'Test Package 1 v2',
            sfLma__Release_Date__c = system.today(),
            sfLma__Sequence__c = 2,
            sfLma__Version__c = '04t4J000000FPjXQAW',
            sfLma__Version_ID__c = '04t4J000000FPjXQAW',
            Package_Version_Password__c = ''
        );
        insert packageVersion2;

        Trialforce_Template__c template = new Trialforce_Template__c
        (
            Trialforce_Template_Id__c = 'TTID001'
        );
        insert template;

        Manifest__c manifest = new Manifest__c
        (
            Name = 'Test',
            Trialforce_Template__c = template.Id
        );
        insert manifest;

        Manifest_Package__c mp1 = new Manifest_Package__c
        (
            Manifest__c = manifest.Id,
            Ordinal__c = 1,
            Package__c = packageObj.Id,
            Package_Version__c = packageVersion.Id
        );
        insert mp1;

        Manifest_Package__c mp2 = new Manifest_Package__c
        (
            Manifest__c = manifest.Id,
            Ordinal__c = 2,
            Package__c = packageObj.Id,
            Package_Version__c = packageVersion2.Id
        );
        insert mp2;

        ProvisioningRequest pr = new ProvisioningRequest();
        pr.ManifestId = manifest.Id;
        pr.Company = 'Test';
        pr.Country = 'GB';
        pr.FirstName = 'Test';
        pr.LastName = 'Test';
        pr.Notes = 'Some notes...';
        pr.Edition = 'Partner Enterprise';
        pr.Language = 'English';
        pr.Email = 'test@salesforce.com';
        pr.Subdomain = 'test-trial';
        pr.TrialDays = 30;
        pr.Username = 'test@testtrial.org';

        ProvisioningRequestHandler.CreateProvisioningRequest(new List<ProvisioningRequest> { pr });

        List<Provisioning_Request__c> requests = [SELECT Id FROM Provisioning_Request__c];
        system.assertNotEquals(0, requests.size());
    }

    @isTest
    static void GetPicklistValuesTest()
    {
        List<CustomPicklist> respList = OrgCheckController.getPicklistValues('SignupRequest', 'Edition');

        system.assertNotEquals(null, respList);
    }

    @isTest
    static void checkOrgIsPBOTest()
    {
        boolean resp = OrgCheckController.checkOrgIsPBO();
        
        system.assertNotEquals(null, resp);
    }

    @isTest
    static void CreateOrgSignupRequestTest()
    {
        sfLma__Package__c packageObj = new sfLma__Package__c
        (
            Name = 'Test Package 1',
            Namespace__c = 'aprv'
        );
        insert packageObj;

        sfLma__Package_Version__c packageVersion = new sfLma__Package_Version__c
        (
            sfLma__Package__c = packageObj.Id,
            Name = 'Test Package 1 v1',
            sfLma__Release_Date__c = system.today(),
            sfLma__Sequence__c = 1,
            sfLma__Version__c = '04t4J000000FPjXQAW',
            sfLma__Version_ID__c = '04t4J000000FPjXQAW',
            Package_Version_Password__c = ''
        );
        insert packageVersion;

        sfLma__Package_Version__c packageVersion2 = new sfLma__Package_Version__c
        (
            sfLma__Package__c = packageObj.Id,
            Name = 'Test Package 1 v2',
            sfLma__Release_Date__c = system.today(),
            sfLma__Sequence__c = 2,
            sfLma__Version__c = '04t4J000000FPjXQAW',
            sfLma__Version_ID__c = '04t4J000000FPjXQAW',
            Package_Version_Password__c = ''
        );
        insert packageVersion2;

        Trialforce_Template__c template = new Trialforce_Template__c
        (
            Trialforce_Template_Id__c = 'TTID001'
        );
        insert template;

        Manifest__c manifest = new Manifest__c
        (
            Name = 'Test',
            Trialforce_Template__c = template.Id
        );
        insert manifest;

        Manifest_Package__c mp1 = new Manifest_Package__c
        (
            Manifest__c = manifest.Id,
            Ordinal__c = 1,
            Package__c = packageObj.Id,
            Package_Version__c = packageVersion.Id
        );
        insert mp1;

        Manifest_Package__c mp2 = new Manifest_Package__c
        (
            Manifest__c = manifest.Id,
            Ordinal__c = 2,
            Package__c = packageObj.Id,
            Package_Version__c = packageVersion2.Id
        );
        insert mp2;

        ProvisioningRequest pr = new ProvisioningRequest();
        pr.ManifestId = manifest.Id;
        pr.Company = 'Test';
        pr.Country = 'GB';
        pr.FirstName = 'Test';
        pr.LastName = 'Test';
        pr.Notes = 'Some notes...';
        pr.Edition = 'Partner Enterprise';
        pr.Language = 'English';
        pr.Email = 'test@salesforce.com';
        pr.Subdomain = 'test-trial';
        pr.TrialDays = 30;
        pr.Username = 'test@testtrial.org';

        ProvisioningRequestHandler.CreateProvisioningRequest(new List<ProvisioningRequest> { pr });

        List<Provisioning_Request__c> requests = [SELECT Id, Company__c, Country__c, FirstName__c, LastName__c, Notes__c, Org_Id__c, PreferredEdition__c, PreferredLanguage__c, SignupEmail__c, Status__c, Subdomain__c, TrialDays__c, Trialforce_Template_Id__c, Username__c FROM Provisioning_Request__c];
        
        ProvisioningRequestHandler.CreateOrgSignupRequest(requests[0]);
    }

    @isTest
    static void CreateOrgSignupRequestNoTrialforceTest()
    {
        sfLma__Package__c packageObj = new sfLma__Package__c
        (
            Name = 'Test Package 1',
            Namespace__c = 'aprv'
        );
        insert packageObj;

        sfLma__Package_Version__c packageVersion = new sfLma__Package_Version__c
        (
            sfLma__Package__c = packageObj.Id,
            Name = 'Test Package 1 v1',
            sfLma__Release_Date__c = system.today(),
            sfLma__Sequence__c = 1,
            sfLma__Version__c = '04t4J000000FPjXQAW',
            sfLma__Version_ID__c = '04t4J000000FPjXQAW',
            Package_Version_Password__c = ''
        );
        insert packageVersion;

        sfLma__Package_Version__c packageVersion2 = new sfLma__Package_Version__c
        (
            sfLma__Package__c = packageObj.Id,
            Name = 'Test Package 1 v2',
            sfLma__Release_Date__c = system.today(),
            sfLma__Sequence__c = 2,
            sfLma__Version__c = '04t4J000000FPjXQAW',
            sfLma__Version_ID__c = '04t4J000000FPjXQAW',
            Package_Version_Password__c = ''
        );
        insert packageVersion2;

        Manifest__c manifest = new Manifest__c
        (
            Name = 'Test'
        );
        insert manifest;

        Manifest_Package__c mp1 = new Manifest_Package__c
        (
            Manifest__c = manifest.Id,
            Ordinal__c = 1,
            Package__c = packageObj.Id,
            Package_Version__c = packageVersion.Id
        );
        insert mp1;

        Manifest_Package__c mp2 = new Manifest_Package__c
        (
            Manifest__c = manifest.Id,
            Ordinal__c = 2,
            Package__c = packageObj.Id,
            Package_Version__c = packageVersion2.Id
        );
        insert mp2;

        ProvisioningRequest pr = new ProvisioningRequest();
        pr.ManifestId = manifest.Id;
        pr.Company = 'Test';
        pr.Country = 'GB';
        pr.FirstName = 'Test';
        pr.LastName = 'Test';
        pr.Notes = 'Some notes...';
        pr.Edition = 'Partner Enterprise';
        pr.Language = 'English';
        pr.Email = 'test@salesforce.com';
        pr.Subdomain = 'test-trial';
        pr.TrialDays = 30;
        pr.Username = 'test@testtrial.org';

        ProvisioningRequestHandler.CreateProvisioningRequest(new List<ProvisioningRequest> { pr });

        List<Provisioning_Request__c> requests = [SELECT Id, Company__c, Country__c, FirstName__c, LastName__c, Notes__c, Org_Id__c, PreferredEdition__c, PreferredLanguage__c, SignupEmail__c, Status__c, Subdomain__c, TrialDays__c, Trialforce_Template_Id__c, Username__c FROM Provisioning_Request__c];
        
        ProvisioningRequestHandler.CreateOrgSignupRequest(requests[0]);
    }
}