force-app/packaged/main/default/objects/Subscriber_Authentication__c/Subscriber_Authentication__c.object-meta.xml
<CustomObject>
    <label>Subscriber Authentication</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers Authentication</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <label>Access</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <label>Instance</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/IsSandbox__c.field-meta.xml
<CustomField>
    <fullName>IsSandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <label>Org Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/Refresh__c.field-meta.xml
<CustomField>
    <fullName>Refresh__c</fullName>
    <label>Refresh</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/packaged/main/default/objects/Subscriber_Authentication__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/packaged/main/default/classes/AuthHelperTest.cls
@isTest
public with sharing class AuthHelperTest 
{
    @isTest
    static void FetchTokensTest()
    {
        Test.setMock(HttpCalloutMock.class, new AuthCalloutMock());

        boolean resp = AuthHelper.fetchTokens('code', false);

        system.assertEquals(true, resp);
    }

    @isTest
    static void FetchUserInfoTest()
    {
        Test.setMock(HttpCalloutMock.class, new AuthCalloutMock());

        Subscriber_Authentication__c authRecord = new Subscriber_Authentication__c
        (
            Access__c = 'access', 
            Instance__c = 'instance', 
            Refresh__c = 'refresh', 
            Org_Id__c = 'orgid', 
            User__c = 'userid',
            IsSandbox__c = true
        );
        insert authRecord;
        
        Test.startTest();
        ComponentResponse resp = ProvisioningRequestHandler.fetchUserInfo(authRecord.Id);
        Test.stopTest();

        system.assertNotEquals('success', resp.MessageType);
    }

    @isTest
    static void GenerateOrgAuthInitialiserTest()
    {
        string resp = AuthHelper.GenerateOrgAuthInitialiser();

        system.assertNotEquals(null, resp);
    }


    @isTest
    static void AuthControllerTest()
    {
        Test.setMock(HttpCalloutMock.class, new AuthCalloutMock());
        
        PageReference pageRef = Page.authHandler;
        Test.setCurrentPage(pageRef);
        
        AuthPageHandler controller = new AuthPageHandler();
        controller.Redirect();
        
        pageRef.getParameters().put('code', 'abc');
        controller.Redirect();
        
        system.assertEquals(true, controller.CloseModal);
    }
}