force-app/packaged/main/default/objects/Provisioner__e/Provisioner__e.object-meta.xml
<CustomObject>
    <label>Provisioner</label>
    <pluralLabel>Provisioner</pluralLabel>
</CustomObject>

force-app/packaged/main/default/objects/Provisioner__e/fields/OrgId__c.field-meta.xml
<CustomField>
    <fullName>OrgId__c</fullName>
    <label>Org Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioner__e/fields/Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Package_Version_Id__c</fullName>
    <label>Package Version Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Manifest__c/Provisioning_Manifest__c.object-meta.xml
<CustomObject>
    <label>Provisioning Manifest</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisioning Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Provisioning_Manifest__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Manifest__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Manifest__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <label>Edition</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Manifest__c/fields/SignupEmail__c.field-meta.xml
<CustomField>
    <fullName>SignupEmail__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ManifestStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Manifest__c/fields/Trialforce_Template__c.field-meta.xml
<CustomField>
    <fullName>Trialforce_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trialforce Template</label>
    <referenceTo>Trialforce_Template__c</referenceTo>
    <relationshipLabel>Provisioning Manifests</relationshipLabel>
    <relationshipName>Provisioning_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Manifest_Package__c/Provisioning_Manifest_Package__c.object-meta.xml
<CustomObject>
    <label>Provisioning Manifest Package</label>
    <nameField>
        <displayFormat>PMP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisioning Manifest Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Provisioning_Manifest_Package__c/fields/Package_Version__c.field-meta.xml
<CustomField>
    <fullName>Package_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Version</label>
    <referenceTo>sfLma__Package_Version__c</referenceTo>
    <relationshipLabel>Provisioning Manifest Packages</relationshipLabel>
    <relationshipName>Provisioning_Manifest_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/packaged/main/default/objects/Provisioning_Manifest_Package__c/fields/Provisioning_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Manifest__c</fullName>
    <label>Provisioning Manifest</label>
    <referenceTo>Provisioning_Manifest__c</referenceTo>
    <relationshipLabel>Provisioning Manifest Packages</relationshipLabel>
    <relationshipName>Provisioning_Manifest_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/packaged/main/default/objects/Trialforce_Template__c/Trialforce_Template__c.object-meta.xml
<CustomObject>
    <label>Trialforce Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trialforce Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/packaged/main/default/objects/Trialforce_Template__c/fields/Trialforce_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Trialforce_Template_Id__c</fullName>
    <label>Trialforce Template Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/packaged/main/default/globalValueSets/ManifestStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <masterLabel>Manifest Status</masterLabel>
</GlobalValueSet>

force-app/packaged/main/default/classes/ProvisioningHelper.cls
public with sharing class ProvisioningHelper 
{
    public static void createSignupRequest(Provisioning_Manifest__c manifest)
    {
        string client_id = '3MVG9xB_D1giir9oHPrfIWI7ADpVTlTAYCqBMnUM6p1C1sh0tvJqboDk.FErGErUR2jxbRlhJIDCvpX0M6iS_';
        string client_secret = '9E75078F6A26D48758C32106A6140F7BF15A9F0F4951F7D8725DB68CF7E22B0B';
        string callback_url = 'https://sandbox-test-developer-edition.cs80.force.com';

        try 
        {
            Type objType = Type.forName('SignupRequest');
            
            if(objType != null)
            {
                sObject signupReq = (sObject)objType.newInstance();

                signupReq.put('Company', manifest.Company__c);
                signupReq.put('ShouldConnectToEnvHub', true);
                signupReq.put('Country', manifest.Country__c);
                signupReq.put('SignupEmail', manifest.SignupEmail__c);
                signupReq.put('FirstName', manifest.FirstName__c);
                signupReq.put('LastName', manifest.LastName__c);
                signupReq.put('Subdomain', manifest.Subdomain__c);
                signupReq.put('IsSignupEmailSuppressed', true);
                signupReq.put('TrialDays', manifest.TrialDays__c);
                signupReq.put('Username', manifest.Username__c);

                if(manifest.Trialforce_Template__r != null)
                {
                    signupReq.put('TemplateId', manifest.Trialforce_Template__r.Trialforce_Template_Id__c);
                }
                else 
                {
                    signupReq.put('Edition', manifest.Edition__c);
                    signupReq.put('PreferredLanguage', manifest.PreferredLanguage__c);
                }

                signupReq.put('ConnectedAppCallbackUrl', callback_url);
                signupReq.put('ConnectedAppConsumerKey', client_id);

                if(!Test.isRunningTest())
                {
                    insert signupReq;
                }
            }
        } 
        catch (Exception ex) 
        {
            // this is an org where SignupRequest does not exist
            manifest.Notes__c = ex.getMessage();
            update manifest;
        }
    }

    public static void installPackage(Provisioning_Manifest_Package__c manifestPackage)
    {
        
    }

    public static void publishPackageInstallChange(List<Provisioning_Manifest_Package__c> manifestPackages)
    {
        List<Provisioner__e> events = new List<Provisioner__e>();

        for(Provisioning_Manifest_Package__c manifestPackage: manifestPackages)
        {
            Provisioner__e ev = new Provisioner__e
            (
                Package_Version_Id__c = manifestPackage.Package_Version__c,
                Status__c = manifestPackage.Status__c,
                OrgId__c = manifestPackage.Provisioning_Manifest__r.Org_Id__c
            );

            events.add(ev);
        }

        if(!events.isEmpty())
        {
            EventBus.publish(events);
        }
    }

    

}